<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Ingredient;
use App\Models\Step;
use App\Models\Category;
use Illuminate\Support\Str;

class RecipeSeeder extends Seeder
{
    public function run()
    {
        // خريطة ربط الكاتيجوري بالـ IDs الأساسية
        $categoryMap = [
            'meal'    => 1,
            'dessert' => 2,
            'drink'   => 3,
            'snack'   => 4,
        ];

        $recipes = [
            [
                'title_en' => 'Pancakes',
                'title_ar' => 'بان كيك',
                'category' => 'meal',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/pancakes.jpg',
                'time' => 20,
                'difficulty' => 'Easy',
                'calories' => 350,
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Soft breakfast pancakes',
                'description_ar' => 'بان كيك طري للفطور',
                'ingredients' => ['flour', 'egg', 'milk', 'sugar'],
                'steps_en' => ['Mix all ingredients together in a bowl', 'Heat a pan or griddle over medium heat', 'Pour batter and cook until edges look dry', 'Flip and cook the other side until golden'],
                'steps_ar' => ['اخلط جميع المكونات معًا في وعاء', 'سخّن المقلاة على نار متوسطة', 'صب العجينة واطهِ حتى تجف الحواف', 'اقلب واطهِ الجانب الآخر حتى يصبح ذهبيًا'],
            ],
            [
                'title_en' => 'Omelette',
                'title_ar' => 'أومليت',
                'category' => 'meal',
                'meal_type' => 'breakfast',
                'temperature' => 'hot',
                'image' => 'asset/img/omelette.jpg',
                'time' => 10,
                'difficulty' => 'Easy',
                'calories' => 200,
                'servings' => 1,
                'cuisine' => 'international',
                'description_en' => 'Classic egg omelette',
                'description_ar' => 'أومليت بالبيض',
                'ingredients' => ['egg', 'salt', 'pepper', 'butter'],
                'steps_en' => ['Beat eggs with salt and pepper in a bowl', 'Heat butter in a non-stick pan over medium heat', 'Pour beaten eggs into the pan', 'Cook until edges set, then fold the omelette in half'],
                'steps_ar' => ['اخفق البيض مع الملح والفلفل في وعاء', 'سخّن الزبدة في مقلاة غير لاصقة على نار متوسطة', 'صب البيض المخفوق في المقلاة', 'اطهِ حتى تتماسك الحواف، ثم اطوِ الأومليت من المنتصف'],
            ],
            [
                'title_en' => 'Pizza',
                'title_ar' => 'بيتزا',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/p3.jpeg',
                'time' => 25,
                'difficulty' => 'Medium',
                'calories' => 300,
                'servings' => 3,
                'cuisine' => 'italian',
                'description_en' => 'Homemade pizza',
                'description_ar' => 'بيتزا منزلية',
                'ingredients' => ['flour', 'cheese', 'butter', 'egg', 'beef'],
                'steps_en' => ['Mix flour with water and knead the dough', 'Let dough rest for 30 minutes', 'Roll out dough and place on baking sheet', 'Add sauce, cheese, and toppings', 'Bake at 200°C for 15-20 minutes until golden'],
                'steps_ar' => ['اخلط الدقيق مع الماء واعجن العجينة', 'اترك العجينة تستريح لمدة 30 دقيقة', 'افرد العجينة وضعها على صينية الخبز', 'أضف الصلصة والجبن والإضافات', 'اخبزها على 200 درجة مئوية لمدة 15-20 دقيقة حتى تصبح ذهبية'],
            ],
            [
                'title_en' => 'Grilled Fish',
                'title_ar' => 'سمك مشوي',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/grilled_fish.jpg',
                'time' => 30,
                'difficulty' => 'Easy',
                'calories' => 350,
                'servings' => 2,
                'cuisine' => 'seafood',
                'description_en' => 'Healthy grilled fish',
                'description_ar' => 'سمك مشوي صحي',
                'ingredients' => ['fish', 'salt', 'pepper', 'lemon', 'olive oil'],
                'steps_en' => ['Clean and pat dry the fish', 'Season with salt, pepper, and lemon juice', 'Brush with olive oil', 'Grill on preheated grill for 4-5 minutes per side', 'Serve immediately with lemon wedges'],
                'steps_ar' => ['نظف السمك وجففه بالمناديل', 'تبّل بالملح والفلفل وعصير الليمون', 'ادهن بزيت الزيتون', 'شوِ على شواية مسخنة لمدة 4-5 دقائق لكل جانب', 'قدّم مباشرة مع شرائح الليمون'],
            ],
            [
                'title_en' => 'Shrimp Pasta',
                'title_ar' => 'مكرونة بالجمبري',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'hot',
                'image' => 'asset/img/shrimp_pasta.jpg',
                'time' => 35,
                'difficulty' => 'Medium',
                'calories' => 500,
                'servings' => 2,
                'cuisine' => 'italian',
                'description_en' => 'Creamy shrimp pasta',
                'description_ar' => 'مكرونة بالجمبري',
                'ingredients' => ['shrimp', 'pasta', 'garlic', 'olive oil', 'salt'],
                'steps_en' => ['Boil pasta until al dente', 'Sauté minced garlic in olive oil', 'Add shrimp and cook until pink', 'Toss pasta with shrimp and garlic', 'Season with salt and serve hot'],
                'steps_ar' => ['اسلق المعكرونة حتى تصبح طرية قليلاً', 'قلّي الثوم المفروم في زيت الزيتون', 'أضف الجمبري واطهِه حتى يصبح وردي اللون', 'امزج المعكرونة مع الجمبري والثوم', 'تبّل بالملح وقدّم ساخنًا'],
            ],
            [
                'title_en' => 'Oats',
                'title_ar' => 'الشوفان',
                'category' => 'meal',
                'meal_type' => 'breakfast',
                'temperature' => 'hot',
                'image' => 'asset/img/oats.jpg',
                'time' => 5,
                'difficulty' => 'Easy',
                'calories' => 150,
                'servings' => 1,
                'cuisine' => 'international',
                'description_en' => 'Healthy oats breakfast',
                'description_ar' => 'فطور صحي من الشوفان',
                'ingredients' => ['oats', 'milk', 'honey'],
                'steps_en' => ["Boil milk or water in a pot", "Add oats and stir well", "Cook for 3-5 minutes over medium heat", "Add honey or your favorite fruits", "Stir and serve warm"],
                'steps_ar' => ["اسلق الحليب أو الماء في وعاء", "أضف الشوفان وحرك جيدًا", "اطهِ لمدة 3-5 دقائق على نار متوسطة", "أضف العسل أو فواكهك المفضلة", "حرك وقدّم ساخنًا"],
            ],
            [
                'title_en' => 'Grilled Chicken',
                'title_ar' => 'دجاج مشوي',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/grilled_chicken.jpg',
                'time' => 40,
                'difficulty' => 'Medium',
                'calories' => 400,
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Delicious grilled chicken',
                'description_ar' => 'دجاج مشوي لذيذ',
                'ingredients' => ['chicken', 'salt', 'pepper', 'olive oil', 'herbs'],
                'steps_en' => ["Pat chicken dry with paper towels", "Rub with olive oil and season with salt, pepper, and herbs", "Preheat grill to medium-high heat", "Grill chicken for 6-7 minutes per side", "Let rest for 5 minutes before serving"],
                'steps_ar' => ["جفف الدجاج بمناديل ورقية", "ادهن بزيت الزيتون وتبّل بالملح والفلفل والأعشاب", "سخّن الشواية على نار عالية", "شوِ الدجاج لمدة 6-7 دقائق لكل جانب", "اترك الدجاج يستريح 5 دقائق قبل التقديم"],
            ],
            [
                'title_en' => 'Pasta',
                'title_ar' => 'معكرونة',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/pasta.jpg',
                'time' => 30,
                'difficulty' => 'Easy',
                'calories' => 450,
                'servings' => 2,
                'cuisine' => 'italian',
                'description_en' => 'Classic pasta dish',
                'description_ar' => 'طبق معكرونة كلاسيكي',
                'ingredients' => ['pasta', 'chicken', 'sauce', 'salt', 'pepper'],
                'steps_en' => ["Boil water and add pasta with salt", "Cook pasta until al dente, then drain", "Cook diced chicken in a separate pan until golden", "Add your favorite sauce to the chicken", "Mix pasta with chicken and sauce, season to taste"],
                'steps_ar' => ["اسلق الماء وأضف المعكرونة مع الملح", "اطهِ المعكرونة حتى تصبح طرية قليلاً، ثم صفّها", "اطهِ الدجاج المقطع في مقلاة منفصلة حتى يصبح ذهبيًا", "أضف صلصتك المفضلة إلى الدجاج", "امزج المعكرونة مع الدجاج والصلصة، وتبّل حسب الرغبة"],
            ],
            [
                'title_en' => 'Burger',
                'title_ar' => 'برجر',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/burger.jpg',
                'time' => 20,
                'difficulty' => 'Medium',
                'calories' => 600,
                'servings' => 1,
                'cuisine' => 'american',
                'description_en' => 'Juicy beef burger',
                'description_ar' => 'برجر اللحم العصير',
                'ingredients' => ['beef', 'bun', 'cheese', 'lettuce', 'tomato'],
                'steps_en' => ["Form ground beef into a patty and season", "Heat a skillet and cook patty for 3-4 minutes per side", "Add cheese and let it melt", "Toast the bun lightly", "Assemble burger with lettuce, tomato, and condiments"],
                'steps_ar' => ["شكّل اللحم المفروم إلى فطيرة وتبّله", "سخّن مقلاة واطهِ الفطيرة 3-4 دقائق لكل جانب", "أضف الجبن واترها تذوب", "حمّص الخبز قليلاً", "رتب البرجر مع الخس والطماطم والصلصات"],
            ],
            [
                'title_en' => 'Chicken Rice',
                'title_ar' => 'أرز بالدجاج',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/chicken_rice.jpg',
                'time' => 45,
                'difficulty' => 'Medium',
                'calories' => 500,
                'servings' => 3,
                'cuisine' => 'middle_eastern',
                'description_en' => 'Aromatic chicken rice',
                'description_ar' => 'أرز عطري بالدجاج',
                'ingredients' => ['chicken', 'rice', 'spices', 'salt', 'oil'],
                'steps_en' => ["Heat oil and sauté diced chicken until cooked", "Add spices and cook for 2 minutes to release flavors", "Rinse rice and add to the chicken", "Stir for 2 minutes, then add water (2:1 ratio)", "Bring to boil, then simmer covered for 15-20 minutes"],
                'steps_ar' => ["سخّن الزيت وقلّي الدجاج المقطع حتى ينضج", "أضف التوابل واطهِها لمدة دقيقتين لإطلاق النكهات", "اشطف الأرز وأضفه إلى الدجاج", "حرك لمدة دقيقتين، ثم أضف الماء (نسبة 2:1)", "اجعله يغلي ثم اطهِه مغطى لمدة 15-20 دقيقة"],
            ],
            [
                'title_en' => 'Lemon Juice',
                'title_ar' => 'عصير الليمون',
                'category' => 'drink',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/lemon_juice.jpg',
                'time' => 5,
                'difficulty' => 'Easy',
                'calories' => 50,
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Fresh lemon juice',
                'description_ar' => 'عصير ليمون طازج',
                'ingredients' => ['lemon', 'water', 'sugar'],
                'steps_en' => ["Cut lemons in half and squeeze the juice", "Strain the juice to remove seeds and pulp", "Mix juice with cold water", "Add sugar or honey to taste", "Stir well and serve over ice"],
                'steps_ar' => ["قطع الليمون نصفين واعصر العصير", "صفّ العصير للتخلص من البذور واللب", "امزج العصير مع الماء البارد", "أضف السكر أو العسل حسب الرغبة", "حرك جيدًا وقدّم مع الثلج"],
            ],
            [
                'title_en' => 'Smoothie',
                'title_ar' => 'سموثي',
                'category' => 'drink',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/smoothie.jpg',
                'time' => 10,
                'difficulty' => 'Easy',
                'calories' => 200,
                'servings' => 1,
                'cuisine' => 'international',
                'description_en' => 'Creamy fruit smoothie',
                'description_ar' => 'سموثي الفواكه الكريمي',
                'ingredients' => ['banana', 'milk', 'yogurt', 'honey'],
                'steps_en' => ["Peel and slice the banana", "Add banana, milk, yogurt, and honey to blender", "Blend until smooth and creamy", "Add ice if desired for extra coldness", "Pour into glass and serve immediately"],
                'steps_ar' => ["قشّر الموز وقطّعه", "أضف الموز والحليب والزبادي والعسل إلى الخلاط", "اخلط حتى يصبح ناعمًا وكريميًا", "أضف الثلج إذا أردت برودة أكثر", "صب في كوب وقدّم مباشرة"],
            ],
            [
                'title_en' => 'Fruit Salad',
                'title_ar' => 'سلطة الفواكه',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/fruit_salad.jpg',
                'time' => 10,
                'difficulty' => 'Easy',
                'calories' => 150,
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Fresh fruit salad',
                'description_ar' => 'سلطة فواكه طازجة',
                'ingredients' => ['apple', 'banana', 'orange', 'yogurt'],
                'steps_en' => ["Wash all fruits thoroughly", "Peel and chop apples, bananas, and oranges", "Place fruits in a large bowl", "Add yogurt and honey", "Toss gently and serve chilled"],
                'steps_ar' => ["اغسل جميع الفواكه جيدًا", "قشّر وقطّع التفاح والموز والبرتقال", "ضع الفواكه في وعاء كبير", "أضف الزبادي والعسل", "اخلط برفق وقدّم مثلجًا"],
            ],
            [
                'title_en' => 'Cookies',
                'title_ar' => 'بسكويت',
                'category' => 'snack',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/cookies.jpg',
                'time' => 25,
                'difficulty' => 'Medium',
                'calories' => 300,
                'servings' => 4,
                'cuisine' => 'international',
                'description_en' => 'Homemade cookies',
                'description_ar' => 'بسكويت منزلي',
                'ingredients' => ['flour', 'sugar', 'butter', 'egg', 'chocolate'],
                'steps_en' => ["Cream butter and sugar until fluffy", "Beat in eggs one at a time", "Mix in flour and chocolate chips", "Drop spoonfuls onto baking sheet", "Bake at 180°C for 12-15 minutes until golden"],
                'steps_ar' => ["اخلط الزبدة والسكر حتى تصبح رقيقة", "أضف البيض واحدة تلو الأخرى", "امزج الدقيق وقطع الشوكولاتة", "ضع ملاعق على صينية الخبز", "اخبزها على 180 درجة مئوية لمدة 12-15 دقيقة حتى تصبح ذهبية"],
            ],
            [
                'title_en' => 'Fried Fish',
                'title_ar' => 'سمك مقلي',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/fried_fish.jpg',
                'time' => 25,
                'difficulty' => 'Medium',
                'calories' => 450,
                'servings' => 2,
                'cuisine' => 'seafood',
                'description_en' => 'Crispy fried fish',
                'description_ar' => 'سمك مقلي مقرمش',
                'ingredients' => ['fish', 'flour', 'salt', 'pepper', 'oil'],
                'steps_en' => ["Pat fish dry and season with salt and pepper", "Mix flour with salt and pepper in a shallow bowl", "Coat fish pieces with flour mixture", "Heat oil in deep pan until hot", "Fry fish until golden and crispy on both sides"],
                'steps_ar' => ["جفف السمك وتبّله بالملح والفلفل", "امزج الدقيق مع الملح والفلفل في وعاء ضحل", "لبّس قطع السمك بخليط الدقيق", "سخّن الزيت في مقلاة عميقة حتى يصبح ساخنًا", "قلِ السمك حتى يصبح ذهبيًا ومقرمشًا من الجانبين"],
            ],
            [
                'title_en' => 'Seafood Rice',
                'title_ar' => 'أرز بحري',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/seafood_rice.jpg',
                'time' => 40,
                'difficulty' => 'Medium',
                'calories' => 520,
                'servings' => 3,
                'cuisine' => 'seafood',
                'description_en' => 'Delicious seafood rice',
                'description_ar' => 'أرز بحري لذيذ',
                'ingredients' => ['rice', 'shrimp', 'fish', 'spices', 'salt'],
                'steps_en' => ["Rinse rice and cook in boiling water until tender", "Drain and set aside", "Cook shrimp and fish in olive oil with spices", "Add the cooked seafood to the rice", "Mix gently and season with salt, then serve hot"],
                'steps_ar' => ["اشطف الأرز واسلقه في ماء مغلي حتى ينضج", "صفّه واتركه جانبًا", "اطهِ الجمبري والسمك بزيت الزيتون والتوابل", "أضف المأكولات البحرية المطهية إلى الأرز", "امزج بحذر وتبّل بالملح، ثم قدّم ساخنًا"],
            ],
            [
                'title_en' => 'Tuna Salad',
                'title_ar' => 'سلطة التونة',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/tuna_salad.jpg',
                'time' => 10,
                'difficulty' => 'Easy',
                'calories' => 300,
                'servings' => 1,
                'cuisine' => 'seafood',
                'description_en' => 'Fresh tuna salad',
                'description_ar' => 'سلطة التونة الطازجة',
                'ingredients' => ['tuna', 'lettuce', 'tomato', 'olive oil', 'lemon'],
                'steps_en' => ["Wash and chop lettuce and tomato", "Arrange vegetables in a salad bowl", "Place tuna on top of vegetables", "Drizzle with olive oil and fresh lemon juice", "Season with salt and pepper, then serve"],
                'steps_ar' => ["اغسل وقطّع الخس والطماطم", "رتب الخضار في وعاء السلطة", "ضع التونة فوق الخضار", "رش بزيت الزيتون وعصير الليمون الطازج", "تبّل بالملح والفلفل، ثم قدّم"],
            ],
            [
                'title_en' => 'Shrimp Soup',
                'title_ar' => 'حساء الجمبري',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'hot',
                'image' => 'asset/img/shrimp_soup.jpg',
                'time' => 30,
                'difficulty' => 'Easy',
                'calories' => 280,
                'servings' => 2,
                'cuisine' => 'seafood',
                'description_en' => 'Delicate shrimp soup',
                'description_ar' => 'حساء الجمبري اللذيذ',
                'ingredients' => ['shrimp', 'onion', 'garlic', 'salt', 'water'],
                'steps_en' => ["Boil water in a large pot", "Add chopped onion and garlic", "Cook for 3-4 minutes until fragrant", "Add shrimp and season with salt", "Simmer for 10-15 minutes until shrimp are pink and cooked"],
                'steps_ar' => ["اسلق الماء في وعاء كبير", "أضف البصل والثوم المفرومين", "اطهِ لمدة 3-4 دقائق حتى تصبح عطرية", "أضف الجمبري وتبّل بالملح", "اترك على نار هادئة لمدة 10-15 دقيقة حتى ينضج الجمبري ويصبح وردي اللون"],
            ],
            [
                'title_en' => 'Fish Sandwich',
                'title_ar' => 'ساندويتش السمك',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/fish_sandwich.jpg',
                'time' => 15,
                'difficulty' => 'Easy',
                'calories' => 400,
                'servings' => 1,
                'cuisine' => 'seafood',
                'description_en' => 'Tasty fish sandwich',
                'description_ar' => 'ساندويتش السمك اللذيذ',
                'ingredients' => ['fish', 'bun', 'lettuce', 'tomato', 'sauce'],
                'steps_en' => ["Pan-fry or grill the fish until cooked through", "Toast the sandwich bun lightly", "Spread sauce on both halves of the bun", "Layer lettuce and tomato on bottom bun", "Place fish on top and close sandwich"],
                'steps_ar' => ["قلِ أو شوِ السمك حتى ينضج تمامًا", "حمّص الخبز قليلاً", "ادهن الصلصة على جانبي الخبز", "رتب الخس والطماطم على نصف الخبز السفلي", "ضع السمك فوقها وأغلق الساندويتش"],
            ],
            // Additional Meal Recipes
            [
                'title_en' => 'Beef Steak',
                'title_ar' => 'ستيك لحم البقر',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'hot',
                'image' => 'asset/img/beef_steak.jpg',
                'time' => 20,
                'difficulty' => 'Medium',
                'calories' => 550,
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Tender beef steak',
                'description_ar' => 'ستيك لحم البقر الطري',
                'ingredients' => ['beef', 'salt', 'pepper', 'butter', 'garlic'],
                'steps_en' => ["Pat beef dry and season generously with salt and pepper", "Heat butter in a cast iron skillet over high heat", "Sear steak for 3-4 minutes per side for medium-rare", "Add minced garlic and baste with butter", "Rest for 5 minutes before serving"],
                'steps_ar' => ["جفف لحم البقر وتبّله جيدًا بالملح والفلفل", "سخّن الزبدة في مقلاة حديدية على نار عالية", "احرق الستيك 3-4 دقائق لكل جانب للحصول على متوسط", "أضف الثوم المفروم واسقِ بالزبدة", "اترك يستريح 5 دقائق قبل التقديم"],
            ],
            [
                'title_en' => 'Lamb Chops',
                'title_ar' => 'قطع لحم الضأن',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'hot',
                'image' => 'asset/img/lamb_chops.jpg',
                'time' => 25,
                'difficulty' => 'Medium',
                'calories' => 480,
                'servings' => 2,
                'cuisine' => 'middle_eastern',
                'description_en' => 'Succulent lamb chops',
                'description_ar' => 'قطع لحم الضأن العصيرة',
                'ingredients' => ['lamb', 'salt', 'pepper', 'rosemary', 'olive oil'],
                'steps_en' => ["Season lamb chops with salt, pepper, and rosemary", "Heat olive oil in a skillet over high heat", "Sear chops for 3-4 minutes per side", "Reduce heat and cook for 2-3 more minutes", "Let rest before serving with herbs"],
                'steps_ar' => ["تبّل قطع الضأن بالملح والفلفل والإكليل", "سخّن زيت الزيتون في مقلاة على نار عالية", "احرق القطع 3-4 دقائق لكل جانب", "قلل النار واطهِ 2-3 دقائق إضافية", "اترك تستريح قبل التقديم مع الأعشاب"],
            ],
            [
                'title_en' => 'Vegetable Stir Fry',
                'title_ar' => 'خضار مقلي بسرعة',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/veggie_stir_fry.jpg',
                'time' => 15,
                'difficulty' => 'Easy',
                'calories' => 250,
                'servings' => 2,
                'cuisine' => 'asian',
                'description_en' => 'Colorful vegetable stir fry',
                'description_ar' => 'خضار ملون مقلي بسرعة',
                'ingredients' => ['broccoli', 'carrot', 'bell pepper', 'soy sauce', 'garlic'],
                'steps_en' => ["Chop vegetables into bite-sized pieces", "Heat oil in a wok or large pan", "Add garlic and cook until fragrant", "Add vegetables and stir fry for 5-7 minutes", "Add soy sauce and serve hot"],
                'steps_ar' => ["قطع الخضار إلى قطع صغيرة", "سخّن الزيت في مقلاة كبيرة", "أضف الثوم واطهِه حتى يصبح عطريًا", "أضف الخضار وقلِها 5-7 دقائق", "أضف صلصة الصويا وقدّم ساخنًا"],
            ],
            [
                'title_en' => 'Meatballs',
                'title_ar' => 'كرات اللحم',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'hot',
                'image' => 'asset/img/meatballs.jpg',
                'time' => 30,
                'difficulty' => 'Medium',
                'calories' => 350,
                'servings' => 4,
                'cuisine' => 'international',
                'description_en' => 'Savory meatballs',
                'description_ar' => 'كرات اللحم اللذيذة',
                'ingredients' => ['beef', 'onion', 'breadcrumbs', 'egg', 'tomato sauce'],
                'steps_en' => ["Mix ground beef, breadcrumbs, egg, and minced onion", "Form into balls about 1 inch in diameter", "Bake at 190°C for 15-20 minutes", "Simmer in tomato sauce for 10 minutes", "Serve hot with pasta or rice"],
                'steps_ar' => ["امزج لحم البقر المفروم والفتات والبيض والبصل المفروم", "شكّل كرات بقطر حوالي بوصة واحدة", "اخبز على 190 درجة مئوية 15-20 دقيقة", "اترك على نار هادئة بصلصة الطماطم 10 دقائق", "قدّم ساخنًا مع المعكرونة أو الأرز"],
            ],
            [
                'title_en' => 'Roast Chicken',
                'title_ar' => 'دجاج مشوي في الفرن',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'hot',
                'image' => 'asset/img/roast_chicken.jpg',
                'time' => 75,
                'difficulty' => 'Medium',
                'calories' => 450,
                'servings' => 4,
                'cuisine' => 'international',
                'description_en' => 'Whole roasted chicken',
                'description_ar' => 'دجاجة مشوية كاملة في الفرن',
                'ingredients' => ['chicken', 'salt', 'pepper', 'herbs', 'lemon'],
                'steps_en' => ["Preheat oven to 200°C", "Pat chicken dry and season inside and out", "Stuff with lemon and herbs", "Place on roasting pan and drizzle with oil", "Roast for 60-70 minutes until golden"],
                'steps_ar' => ["سخّن الفرن إلى 200 درجة مئوية", "جفف الدجاجة وتبّلها من الداخل والخارج", "محّشها بالليمون والأعشاب", "ضعها على صينية الشواء واسكب عليها الزيت", "اشوها 60-70 دقيقة حتى تصبح ذهبية"],
            ],
            // Additional Dessert Recipes
            [
                'title_en' => 'Chocolate Cake',
                'title_ar' => 'كعكة الشوكولاتة',
                'category' => 'dessert',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/chocolate_cake.jpg',
                'time' => 50,
                'difficulty' => 'Medium',
                'calories' => 400,
                'servings' => 6,
                'cuisine' => 'international',
                'description_en' => 'Rich chocolate cake',
                'description_ar' => 'كعكة الشوكولاتة الغنية',
                'ingredients' => ['flour', 'cocoa', 'sugar', 'egg', 'butter'],
                'steps_en' => ["Cream butter and sugar until light", "Beat in eggs one at a time", "Mix flour and cocoa powder", "Fold dry ingredients into butter mixture", "Pour into greased pan and bake at 175°C for 35-40 minutes"],
                'steps_ar' => ["اخلط الزبدة والسكر حتى تصبح خفيفة", "أضف البيض واحدة تلو الأخرى", "امزج الدقيق وكاكاو البودرة", "أضف المكونات الجافة إلى خليط الزبدة", "صب في قالب مدهون واخبز على 175 درجة مئوية 35-40 دقيقة"],
            ],
            [
                'title_en' => 'Brownies',
                'title_ar' => 'براونيز',
                'category' => 'dessert',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/brownies.jpg',
                'time' => 35,
                'difficulty' => 'Easy',
                'calories' => 350,
                'servings' => 8,
                'cuisine' => 'international',
                'description_en' => 'Fudgy brownies',
                'description_ar' => 'براونيز طري',
                'ingredients' => ['chocolate', 'butter', 'sugar', 'egg', 'flour'],
                'steps_en' => ["Melt chocolate and butter together", "Mix in sugar and beaten eggs", "Fold in flour and pour into pan", "Bake at 180°C for 25-30 minutes", "Cool and cut into squares"],
                'steps_ar' => ["ذوّب الشوكولاتة والزبدة معًا", "امزج السكر والبيض المخفوق", "أضف الدقيق وصب في القالب", "اخبز على 180 درجة مئوية 25-30 دقيقة", "اترك تبرد وقطّع إلى مربعات"],
            ],
            [
                'title_en' => 'Cheesecake',
                'title_ar' => 'تشيزكيك',
                'category' => 'dessert',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/cheesecake.jpg',
                'time' => 90,
                'difficulty' => 'Hard',
                'calories' => 450,
                'servings' => 8,
                'cuisine' => 'international',
                'description_en' => 'Creamy cheesecake',
                'description_ar' => 'تشيزكيك كريمي',
                'ingredients' => ['cream cheese', 'sugar', 'egg', 'graham cracker', 'vanilla'],
                'steps_en' => ["Crush graham crackers and mix with melted butter for crust", "Press into pan and bake at 160°C for 10 minutes", "Mix cream cheese, sugar, eggs, and vanilla", "Pour over crust and bake at 165°C for 50-60 minutes", "Cool completely and refrigerate overnight"],
                'steps_ar' => ["سحق بسكويت جراهام وامزجه مع الزبدة المذابة للقاع", "اضغط في القالب واخبز على 160 درجة مئوية 10 دقائق", "امزج كريمة الجبن والسكر والبيض والفانيليا", "صب فوق القاع واخبز على 165 درجة مئوية 50-60 دقيقة", "اترك يبرد تمامًا وضع في الثلاجة طوال الليل"],
            ],
            [
                'title_en' => 'Tiramisu',
                'title_ar' => 'تيراميسو',
                'category' => 'dessert',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/tiramisu.jpg',
                'time' => 20,
                'difficulty' => 'Medium',
                'calories' => 380,
                'servings' => 6,
                'cuisine' => 'italian',
                'description_en' => 'Italian tiramisu dessert',
                'description_ar' => 'حلوى تيراميسو الإيطالية',
                'ingredients' => ['ladyfinger', 'mascarpone', 'coffee', 'cocoa', 'egg'],
                'steps_en' => ["Brew strong coffee and let cool", "Whip mascarpone with sugar and egg yolks", "Dip ladyfingers in coffee and layer", "Spread mascarpone mixture on each layer", "Dust with cocoa and refrigerate for 4 hours"],
                'steps_ar' => ["اصنع قهوة قوية واترها تبرد", "اخفق ماسكاربوني مع السكر وصفار البيض", "اغمس بسكويت الإصبع في القهوة وطبق طبقات", "ادهن خليط ماسكاربوني على كل طبقة", "رش كاكاو واترك في الثلاجة 4 ساعات"],
            ],
            [
                'title_en' => 'Ice Cream',
                'title_ar' => 'آيس كريم',
                'category' => 'dessert',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/ice_cream.jpg',
                'time' => 10,
                'difficulty' => 'Easy',
                'calories' => 200,
                'servings' => 4,
                'cuisine' => 'international',
                'description_en' => 'Homemade vanilla ice cream',
                'description_ar' => 'آيس كريم الفانيليا المنزلي',
                'ingredients' => ['cream', 'milk', 'sugar', 'vanilla', 'egg'],
                'steps_en' => ["Heat milk and cream together", "Mix egg yolks with sugar until pale", "Slowly add warm milk to egg mixture", "Cook in double boiler until it coats a spoon", "Chill and churn in ice cream maker"],
                'steps_ar' => ["سخّن الحليب والقشطة معًا", "امزج صفار البيض مع السكر حتى يصبح فاتحًا", "أضف الحليب الدافئ ببطء إلى خليط البيض", "اطهِ في حمام مائي حتى تصبح سميكة", "برّد واخلط في آلة صنع الآيس كريم"],
            ],
            // Additional Drink Recipes
            [
                'title_en' => 'Orange Juice',
                'title_ar' => 'عصير البرتقال',
                'category' => 'drink',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/orange_juice.jpg',
                'time' => 5,
                'difficulty' => 'Easy',
                'calories' => 110,
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Fresh squeezed orange juice',
                'description_ar' => 'عصير برتقال طازج مصنوع من البيت',
                'ingredients' => ['orange', 'water', 'sugar'],
                'steps_en' => ["Cut oranges in half and squeeze the juice", "Strain through a fine mesh", "Mix with water if preferred", "Add sugar to taste", "Serve chilled with ice"],
                'steps_ar' => ["قطع البرتقال نصفين واعصر العصير", "صفّ من خلال غربال ناعم", "امزج مع الماء إذا رغبت", "أضف السكر حسب الرغبة", "قدّم باردًا مع الثلج"],
            ],
            [
                'title_en' => 'Strawberry Juice',
                'title_ar' => 'عصير الفراولة',
                'category' => 'drink',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/strawberry_juice.jpg',
                'time' => 10,
                'difficulty' => 'Easy',
                'calories' => 80,
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Fresh strawberry juice',
                'description_ar' => 'عصير الفراولة الطازج',
                'ingredients' => ['strawberry', 'water', 'honey'],
                'steps_en' => ["Wash and hull strawberries", "Blend strawberries with water", "Strain through fine mesh", "Add honey to taste", "Serve cold with ice"],
                'steps_ar' => ["اغسل الفراولة وأزل الرؤوس", "اخلط الفراولة مع الماء", "صفّ من خلال غربال ناعم", "أضف العسل حسب الرغبة", "قدّم باردًا مع الثلج"],
            ],
            [
                'title_en' => 'Mango Lassi',
                'title_ar' => 'لاسي المانجو',
                'category' => 'drink',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/mango_lassi.jpg',
                'time' => 8,
                'difficulty' => 'Easy',
                'calories' => 180,
                'servings' => 2,
                'cuisine' => 'asian',
                'description_en' => 'Creamy mango yogurt drink',
                'description_ar' => 'شراب اللبن والمانجو الكريمي',
                'ingredients' => ['mango', 'yogurt', 'milk', 'honey'],
                'steps_en' => ["Peel and chop fresh mango", "Add to blender with yogurt and milk", "Blend until smooth", "Add honey to taste", "Serve chilled"],
                'steps_ar' => ["قشّر المانجو وقطّعها", "أضفها إلى الخلاط مع الزبادي والحليب", "اخلط حتى تصبح ناعمة", "أضف العسل حسب الرغبة", "قدّم مثلجة"],
            ],
            [
                'title_en' => 'Iced Tea',
                'title_ar' => 'شاي مثلج',
                'category' => 'drink',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/iced_tea.jpg',
                'time' => 15,
                'difficulty' => 'Easy',
                'calories' => 30,
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Refreshing iced tea',
                'description_ar' => 'شاي مثلج منعش',
                'ingredients' => ['tea', 'water', 'lemon', 'sugar'],
                'steps_en' => ["Brew strong tea and let cool", "Pour into glasses filled with ice", "Add lemon juice and sugar", "Stir well", "Serve immediately"],
                'steps_ar' => ["اصنع شاي قوي واترها تبرد", "صب في أكواب ممتلئة بالثلج", "أضف عصير الليمون والسكر", "حرك جيدًا", "قدّم مباشرة"],
            ],
            [
                'title_en' => 'Coffee',
                'title_ar' => 'قهوة',
                'category' => 'drink',
                'meal_type' => 'breakfast',
                'temperature' => 'hot',
                'image' => 'asset/img/coffee.jpg',
                'time' => 5,
                'difficulty' => 'Easy',
                'calories' => 10,
                'servings' => 1,
                'cuisine' => 'international',
                'description_en' => 'Hot brewed coffee',
                'description_ar' => 'قهوة ساخنة مصنوعة من البيت',
                'ingredients' => ['coffee beans', 'water', 'sugar'],
                'steps_en' => ["Grind coffee beans to medium fineness", "Brew with hot water", "Add sugar and milk if desired", "Pour into cup", "Serve hot"],
                'steps_ar' => ["اطحن حبوب القهوة لدرجة متوسطة", "اصنع مع الماء الساخن", "أضف السكر والحليب إذا رغبت", "صب في كوب", "قدّم ساخنة"],
            ],
            // Additional Snack Recipes
            [
                'title_en' => 'Nachos',
                'title_ar' => 'ناتشوز',
                'category' => 'snack',
                'meal_type' => 'dinner',
                'temperature' => 'hot',
                'image' => 'asset/img/nachos.jpg',
                'time' => 15,
                'difficulty' => 'Easy',
                'calories' => 320,
                'servings' => 2,
                'cuisine' => 'mexican',
                'description_en' => 'Crispy nachos with cheese',
                'description_ar' => 'ناتشوز مقرمشة بالجبن',
                'ingredients' => ['tortilla chips', 'cheese', 'jalapeño', 'salsa'],
                'steps_en' => ["Arrange tortilla chips on a baking sheet", "Sprinkle cheese evenly over chips", "Top with sliced jalapeños", "Bake at 190°C for 5-7 minutes until cheese melts", "Top with salsa and serve hot"],
                'steps_ar' => ["رتب رقائق التورتيلا على صينية الخبز", "رش الجبن بالتساوي على الرقائق", "أضف شرائح الفلفل الحار فوقها", "اخبز على 190 درجة مئوية 5-7 دقائق حتى تذوب الجبن", "أضف الصلصة وقدّم ساخنة"],
            ],
            [
                'title_en' => 'Popcorn',
                'title_ar' => 'فشار',
                'category' => 'snack',
                'meal_type' => 'dinner',
                'temperature' => 'hot',
                'image' => 'asset/img/popcorn.jpg',
                'time' => 10,
                'difficulty' => 'Easy',
                'calories' => 150,
                'servings' => 3,
                'cuisine' => 'international',
                'description_en' => 'Buttered popcorn',
                'description_ar' => 'فشار بالزبدة',
                'ingredients' => ['popcorn kernels', 'butter', 'salt'],
                'steps_en' => ["Heat oil in a large pot with a lid", "Add popcorn kernels and cover", "Wait until popping slows down to 2-3 seconds between pops", "Remove from heat and pour into bowl", "Drizzle with melted butter and salt"],
                'steps_ar' => ["سخّن الزيت في وعاء كبير بغطاء", "أضف حبات الفشار وغطّ الوعاء", "انتظر حتى يتباطأ الفرقعة إلى 2-3 ثوان بين الفرقعات", "أزل من النار وصب في وعاء", "رش بالزبدة المذابة والملح"],
            ],
            [
                'title_en' => 'Chips and Guacamole',
                'title_ar' => 'رقائق مع الجواكامولي',
                'category' => 'snack',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/chips_guac.jpg',
                'time' => 10,
                'difficulty' => 'Easy',
                'calories' => 280,
                'servings' => 2,
                'cuisine' => 'mexican',
                'description_en' => 'Crispy chips with guacamole',
                'description_ar' => 'رقائق مقرمشة مع الجواكامولي',
                'ingredients' => ['tortilla chips', 'avocado', 'lime', 'cilantro', 'salt'],
                'steps_en' => ["Cut avocados in half and remove pit", "Scoop into a bowl and mash lightly", "Add lime juice, cilantro, and salt", "Mix gently", "Serve with tortilla chips"],
                'steps_ar' => ["قطع الأفوكادو نصفين وأزل النواة", "ضعها في وعاء واسحقها قليلاً", "أضف عصير الليمون والكزبرة والملح", "امزج بحذر", "قدّم مع رقائق التورتيلا"],
            ],
            [
                'title_en' => 'Fruit Trail Mix',
                'title_ar' => 'خليط المكسرات والفواكه',
                'category' => 'snack',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/trail_mix.jpg',
                'time' => 5,
                'difficulty' => 'Easy',
                'calories' => 220,
                'servings' => 4,
                'cuisine' => 'international',
                'description_en' => 'Nutritious trail mix',
                'description_ar' => 'خليط الفواكه والمكسرات الغذائي',
                'ingredients' => ['almonds', 'raisins', 'dried cranberry', 'dark chocolate'],
                'steps_en' => ["Combine almonds, raisins, and dried cranberries in a bowl", "Add dark chocolate chips", "Mix thoroughly", "Store in airtight container", "Enjoy as a healthy snack"],
                'steps_ar' => ["امزج اللوز والزبيب والتوت البري المجفف في وعاء", "أضف رقائق الشوكولاتة الداكنة", "امزج جيدًا", "احفظ في وعاء محكم الإغلاق", "استمتع به كوجبة خفيفة صحية"],
            ],
            [
                'title_en' => 'Yogurt Parfait',
                'title_ar' => 'باريه الزبادي',
                'category' => 'snack',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/yogurt_parfait.jpg',
                'time' => 5,
                'difficulty' => 'Easy',
                'calories' => 180,
                'servings' => 1,
                'cuisine' => 'international',
                'description_en' => 'Layered yogurt and fruit',
                'description_ar' => 'زبادي وفواكه بطبقات',
                'ingredients' => ['yogurt', 'granola', 'berry', 'honey'],
                'steps_en' => ["Pour yogurt into a glass", "Add layer of granola", "Top with mixed berries", "Add another yogurt layer", "Drizzle with honey and serve"],
                'steps_ar' => ["صب الزبادي في كوب", "أضف طبقة من الجرانولا", "أضف التوت المختلط فوقها", "أضف طبقة أخرى من الزبادي", "رش بالعسل وقدّم"],
            ],
        ];

        foreach ($recipes as $data) {
            // جلب الـ ID المناسب من الـ Map أو افتراض 1 لو مش موجود
            $catId = $categoryMap[$data['category']] ?? 1;

            $recipe = Recipe::create([
                'title_en' => $data['title_en'],
                'title_ar' => $data['title_ar'],
                'category_id' => $catId,
                'meal_type' => $data['meal_type'],
                'temperature' => $data['temperature'],
                'slug' => Str::slug($data['title_en']) . '-' . uniqid(),
                'image' => $data['image'],
                'time' => $data['time'], // أرقام فقط الآن
                'difficulty' => $data['difficulty'],
                'cuisine' => $data['cuisine'],
                'calories' => (int)$data['calories'],
                'servings' => $data['servings'],
                'description_en' => $data['description_en'],
                'description_ar' => $data['description_ar'],
                // Legacy JSON support
                'steps' => json_encode(['en' => $data['steps_en'], 'ar' => $data['steps_ar']], JSON_UNESCAPED_UNICODE),
                'ingredients' => json_encode($data['ingredients']),
            ]);

            // ربط المكونات (Pivot)
            $ingredientIds = Ingredient::whereIn('name_en', $data['ingredients'])->pluck('id');
            foreach ($ingredientIds as $ingId) {
                $recipe->ingredients()->attach($ingId, ['quantity' => '1', 'unit' => 'piece']);
            }

            // إضافة الخطوات في الجدول المنفصل
            foreach ($data['steps_en'] as $index => $stepEn) {
                Step::create([
                    'recipe_id' => $recipe->id,
                    'step_number' => $index + 1,
                    'instruction_en' => $stepEn,
                    'instruction_ar' => $data['steps_ar'][$index],
                ]);
            }
        }
    }
}
