<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Ingredient;
use Illuminate\Support\Str;

class RecipeSeeder extends Seeder
{
    public function run()
    {
        $recipes = [

            [
                'title_en' => 'Pancakes',
                'title_ar' => 'بان كيك',
                'category' => 'meal',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/pancakes.jpg',
                'time' => '20 min',
                'difficulty' => 'Easy',
                'calories' => '350',
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Soft breakfast pancakes',
                'description_ar' => 'بان كيك طري للفطور',
                'ingredients' => ['flour', 'egg', 'milk', 'sugar'],
                'steps' => ['Mix all ingredients', 'Heat a pan', 'Cook both sides'],
            ],

            [
                'title_en' => 'Omelette',
                'title_ar' => 'أومليت',
                'category' => 'meal',
                'meal_type' => 'breakfast',
                'temperature' => 'hot',
                'image' => 'asset/img/omelette.jpg',
                'time' => '10 min',
                'difficulty' => 'Easy',
                'calories' => '200',
                'servings' => 1,
                'cuisine' => 'international',
                'description_en' => 'Classic egg omelette',
                'description_ar' => 'أومليت بالبيض',
                'ingredients' => ['egg', 'salt', 'pepper', 'butter'],
                'steps' => ['Beat eggs', 'Heat butter', 'Cook until set'],
            ],

            [
                'title_en' => 'Pizza',
                'title_ar' => 'بيتزا',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/p3.jpeg',
                'time' => '25 min',
                'difficulty' => 'Medium',
                'calories' => '300',
                'servings' => 3,
                'cuisine' => 'italian',
                'description_en' => 'Homemade pizza',
                'description_ar' => 'بيتزا منزلية',
                'ingredients' => ['flour', 'cheese', 'butter', 'egg', 'beef'],
                'steps' => ['Prepare dough', 'Add toppings', 'Bake until ready'],
            ],

            [
                'title_en' => 'Grilled Fish',
                'title_ar' => 'سمك مشوي',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/grilled_fish.jpg',
                'time' => '30 min',
                'difficulty' => 'Easy',
                'calories' => '350',
                'servings' => 2,
                'cuisine' => 'seafood',
                'description_en' => 'Healthy grilled fish',
                'description_ar' => 'سمك مشوي صحي',
                'ingredients' => ['fish', 'salt', 'pepper', 'lemon', 'olive oil'],
                'steps' => ['Season fish', 'Grill', 'Serve'],
            ],

            [
                'title_en' => 'Shrimp Pasta',
                'title_ar' => 'مكرونة بالجمبري',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'hot',
                'image' => 'asset/img/shrimp_pasta.jpg',
                'time' => '35 min',
                'difficulty' => 'Medium',
                'calories' => '500',
                'servings' => 2,
                'cuisine' => 'italian',
                'description_en' => 'Creamy shrimp pasta',
                'description_ar' => 'مكرونة بالجمبري',
                'ingredients' => ['shrimp', 'pasta', 'garlic', 'olive oil', 'salt'],
                'steps' => ['Boil pasta', 'Cook shrimp', 'Mix together'],
            ],


            [
                'title_en' => 'Oats',
                'title_ar' => 'الشوفان',
                'category' => 'meal',
                'meal_type' => 'breakfast',
                'temperature' => 'hot',
                'image' => 'asset/img/oats.jpg',
                'time' => '5 min',
                'difficulty' => 'Easy',
                'calories' => '150',
                'servings' => 1,
                'cuisine' => 'international',
                'description_en' => 'Healthy oats breakfast',
                'description_ar' => 'فطور صحي من الشوفان',
                'ingredients' => ['oats', 'milk', 'honey'],
                'steps' => [
                    "Boil milk or water",
                    "Add oats and cook 3-5 min",
                    "Add honey or fruits"
                ],
            ],
            [
                'title_en' => 'Grilled Chicken',
                'title_ar' => 'دجاج مشوي',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/grilled_chicken.jpg',
                'time' => '40 min',
                'difficulty' => 'Medium',
                'calories' => '400',
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Delicious grilled chicken',
                'description_ar' => 'دجاج مشوي لذيذ',
                'ingredients' => ['chicken', 'salt', 'pepper', 'olive oil', 'herbs'],
                'steps' => [
                    "Season the chicken",
                    "Grill on pan or oven",
                    "Serve hot"
                ],
            ],
            [
                'title_en' => 'Pasta',
                'title_ar' => 'معكرونة',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/pasta.jpg',
                'time' => '30 min',
                'difficulty' => 'Easy',
                'calories' => '450',
                'servings' => 2,
                'cuisine' => 'italian',
                'description_en' => 'Classic pasta dish',
                'description_ar' => 'طبق معكرونة كلاسيكي',
                'ingredients' => ['pasta', 'chicken', 'sauce', 'salt', 'pepper'],
                'steps' => [
                    "Boil pasta",
                    "Cook chicken/vegetables",
                    "Mix with sauce"
                ],
            ],
            [
                'title_en' => 'Burger',
                'title_ar' => 'برجر',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/burger.jpg',
                'time' => '20 min',
                'difficulty' => 'Medium',
                'calories' => '600',
                'servings' => 1,
                'cuisine' => 'american',
                'description_en' => 'Juicy beef burger',
                'description_ar' => 'برجر اللحم العصير',
                'ingredients' => ['beef', 'bun', 'cheese', 'lettuce', 'tomato'],
                'steps' => [
                    "Cook beef patty",
                    "Assemble burger with bun and toppings"
                ],
            ],
            [
                'title_en' => 'Chicken Rice',
                'title_ar' => 'أرز بالدجاج',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/chicken_rice.jpg',
                'time' => '45 min',
                'difficulty' => 'Medium',
                'calories' => '500',
                'servings' => 3,
                'cuisine' => 'middle_eastern',
                'description_en' => 'Aromatic chicken rice',
                'description_ar' => 'أرز عطري بالدجاج',
                'ingredients' => ['chicken', 'rice', 'spices', 'salt', 'oil'],
                'steps' => [
                    "Cook rice",
                    "Cook chicken with spices",
                    "Mix and serve"
                ],
            ],
            [
                'title_en' => 'Lemon Juice',
                'title_ar' => 'عصير الليمون',
                'category' => 'drink',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/lemon_juice.jpg',
                'time' => '5 min',
                'difficulty' => 'Easy',
                'calories' => '50',
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Fresh lemon juice',
                'description_ar' => 'عصير ليمون طازج',
                'ingredients' => ['lemon', 'water', 'sugar'],
                'steps' => [
                    "Squeeze lemons",
                    "Mix with water and sugar",
                    "Serve chilled"
                ],
            ],
            [
                'title_en' => 'Smoothie',
                'title_ar' => 'سموثي',
                'category' => 'drink',
                'meal_type' => 'breakfast',
                'temperature' => 'cold',
                'image' => 'asset/img/smoothie.jpg',
                'time' => '10 min',
                'difficulty' => 'Easy',
                'calories' => '200',
                'servings' => 1,
                'cuisine' => 'international',
                'description_en' => 'Creamy fruit smoothie',
                'description_ar' => 'سموثي الفواكه الكريمي',
                'ingredients' => ['banana', 'milk', 'yogurt', 'honey'],
                'steps' => [
                    "Blend all ingredients",
                    "Serve immediately"
                ],
            ],
            [
                'title_en' => 'Fruit Salad',
                'title_ar' => 'سلطة الفواكه',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/fruit_salad.jpg',
                'time' => '10 min',
                'difficulty' => 'Easy',
                'calories' => '150',
                'servings' => 2,
                'cuisine' => 'international',
                'description_en' => 'Fresh fruit salad',
                'description_ar' => 'سلطة فواكه طازجة',
                'ingredients' => ['apple', 'banana', 'orange', 'yogurt'],
                'steps' => [
                    "Cut fruits",
                    "Mix with honey or yogurt",
                    "Serve fresh"
                ],
            ],
            [
                'title_en' => 'Cookies',
                'title_ar' => 'بسكويت',
                'category' => 'snack',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/cookies.jpg',
                'time' => '25 min',
                'difficulty' => 'Medium',
                'calories' => '300',
                'servings' => 4,
                'cuisine' => 'international',
                'description_en' => 'Homemade cookies',
                'description_ar' => 'بسكويت منزلي',
                'ingredients' => ['flour', 'sugar', 'butter', 'egg', 'chocolate'],
                'steps' => [
                    "Mix all ingredients",
                    "Shape cookies",
                    "Bake 12-15 min at 180°C"
                ],
            ],
            [
                'title_en' => 'Fried Fish',
                'title_ar' => 'سمك مقلي',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/fried_fish.jpg',
                'time' => '25 min',
                'difficulty' => 'Medium',
                'calories' => '450',
                'servings' => 2,
                'cuisine' => 'seafood',
                'description_en' => 'Crispy fried fish',
                'description_ar' => 'سمك مقلي مقرمش',
                'ingredients' => ['fish', 'flour', 'salt', 'pepper', 'oil'],
                'steps' => [
                    "Season the fish",
                    "Coat with flour",
                    "Fry in hot oil until golden"
                ],
            ],
            [
                'title_en' => 'Seafood Rice',
                'title_ar' => 'أرز بحري',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/seafood_rice.jpg',
                'time' => '40 min',
                'difficulty' => 'Medium',
                'calories' => '520',
                'servings' => 3,
                'cuisine' => 'seafood',
                'description_en' => 'Delicious seafood rice',
                'description_ar' => 'أرز بحري لذيذ',
                'ingredients' => ['rice', 'shrimp', 'fish', 'spices', 'salt'],
                'steps' => [
                    "Cook rice",
                    "Cook seafood with spices",
                    "Mix seafood with rice and serve"
                ],
            ],
            [
                'title_en' => 'Tuna Salad',
                'title_ar' => 'سلطة التونة',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'cold',
                'image' => 'asset/img/tuna_salad.jpg',
                'time' => '10 min',
                'difficulty' => 'Easy',
                'calories' => '300',
                'servings' => 1,
                'cuisine' => 'seafood',
                'description_en' => 'Fresh tuna salad',
                'description_ar' => 'سلطة التونة الطازجة',
                'ingredients' => ['tuna', 'lettuce', 'tomato', 'olive oil', 'lemon'],
                'steps' => [
                    "Prepare vegetables",
                    "Add tuna",
                    "Mix with olive oil and lemon"
                ],
            ],
            [
                'title_en' => 'Shrimp Soup',
                'title_ar' => 'حساء الجمبري',
                'category' => 'meal',
                'meal_type' => 'dinner',
                'temperature' => 'hot',
                'image' => 'asset/img/shrimp_soup.jpg',
                'time' => '30 min',
                'difficulty' => 'Easy',
                'calories' => '280',
                'servings' => 2,
                'cuisine' => 'seafood',
                'description_en' => 'Delicate shrimp soup',
                'description_ar' => 'حساء الجمبري اللذيذ',
                'ingredients' => ['shrimp', 'onion', 'garlic', 'salt', 'water'],
                'steps' => [
                    "Boil water",
                    "Add shrimp and vegetables",
                    "Cook until shrimp is done"
                ],
            ],
            [
                'title_en' => 'Fish Sandwich',
                'title_ar' => 'ساندويتش السمك',
                'category' => 'meal',
                'meal_type' => 'lunch',
                'temperature' => 'hot',
                'image' => 'asset/img/fish_sandwich.jpg',
                'time' => '15 min',
                'difficulty' => 'Easy',
                'calories' => '400',
                'servings' => 1,
                'cuisine' => 'seafood',
                'description_en' => 'Tasty fish sandwich',
                'description_ar' => 'ساندويتش السمك اللذيذ',
                'ingredients' => ['fish', 'bun', 'lettuce', 'tomato', 'sauce'],
                'steps' => [
                    "Cook the fish",
                    "Prepare bun and vegetables",
                    "Assemble the sandwich"
                ],
            ],
        ];

        foreach ($recipes as $data) {

            $recipe = Recipe::create([
                'title' => $data['title_en'],
                'title_en' => $data['title_en'],
                'title_ar' => $data['title_ar'],
                'category' => $data['category'],
                'meal_type' => $data['meal_type'],
                'temperature' => $data['temperature'],
                'slug' => Str::slug($data['title_en']) . '-' . uniqid(),
                'image' => $data['image'],
                'time' => $data['time'],
                'difficulty' => $data['difficulty'],
                'cuisine' => $data['cuisine'],
                'nutrition' => json_encode(['calories' => $data['calories']]),
                'calories' => $data['calories'],
                'servings' => $data['servings'],
                'steps' => json_encode($data['steps']),
                'description_en' => $data['description_en'],
                'description_ar' => $data['description_ar'],
            ]);

            $ingredientIds = Ingredient::whereIn('name', $data['ingredients'])->pluck('id');
            $recipe->ingredients()->sync($ingredientIds);
        }
    }
}
